CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "User" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" character varying(50) NOT NULL,
        "NormalizedUserName" character varying(50) NOT NULL,
        "PasswordHash" character varying(256) NOT NULL,
        "Email" character varying(200) NOT NULL,
        "IsAdmin" boolean NOT NULL,
        "IsEmailVerified" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "LastLoginAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_User" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "AgentMemories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Key" text NOT NULL,
        "Value" text NOT NULL,
        "Category" text NOT NULL,
        "Tags" text,
        "Importance" smallint NOT NULL,
        "AccessedCount" integer NOT NULL,
        "Source" text,
        "LastAccessedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_AgentMemories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AgentMemories_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "AIActionLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "ActionType" character varying(50) NOT NULL,
        "IntentDesc" character varying(500),
        "TargetType" character varying(20),
        "TargetId" integer,
        "PayloadJson" text,
        "Decision" character varying(20) NOT NULL,
        "DecidedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_AIActionLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AIActionLogs_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "ChatProject" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Color" character varying(20) NOT NULL,
        "Icon" character varying(10) NOT NULL,
        "Instructions" character varying(4000),
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_ChatProject" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ChatProject_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "DailyBriefings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "BriefDate" date NOT NULL,
        "Content" text NOT NULL,
        "SourcesJson" text,
        "Model" character varying(50),
        "GeneratedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_DailyBriefings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DailyBriefings_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "EmailVerifyToken" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Token" character varying(200) NOT NULL,
        "Type" character varying(50) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsUsed" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_EmailVerifyToken" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EmailVerifyToken_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "InboxItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Raw" character varying(2000) NOT NULL,
        "Source" smallint NOT NULL,
        "Status" smallint NOT NULL,
        "AiParse" text,
        "AiModel" character varying(50),
        "CorrectionNote" character varying(500),
        "Error" character varying(500),
        "TriagedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_InboxItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_InboxItems_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "LifeLog" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Content" text NOT NULL,
        "Mood" character varying(50),
        "ImagePath" character varying(500),
        "LogDate" date NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_LifeLog" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LifeLog_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "Memo" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Section" character varying(20) NOT NULL,
        "Content" character varying(1000) NOT NULL,
        "RemindAt" timestamp with time zone,
        "RemindMethods" smallint NOT NULL,
        "EmailReminderSent" boolean NOT NULL,
        "PopupAcknowledged" boolean NOT NULL,
        "RemindedAt" timestamp with time zone,
        "Priority" smallint NOT NULL,
        "IsPinned" boolean NOT NULL,
        "IsDone" boolean NOT NULL,
        "IsArchived" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_Memo" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Memo_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "RefreshToken" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "TokenHash" character varying(200) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsRevoked" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_RefreshToken" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefreshToken_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "ScheduledTask" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Description" character varying(2000) NOT NULL,
        "ExecuteAt" timestamp with time zone NOT NULL,
        "Status" character varying(20) NOT NULL,
        "Result" character varying(5000),
        "ErrorMessage" character varying(2000),
        "NotifyEmail" boolean NOT NULL,
        "ExecutedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_ScheduledTask" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ScheduledTask_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "WeeklyReport" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "WeekStart" date NOT NULL,
        "WeekEnd" date NOT NULL,
        "Content" text NOT NULL,
        "GeneratedAt" timestamp with time zone NOT NULL,
        "IsEdited" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_WeeklyReport" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_WeeklyReport_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "WeeklyReportReference" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "FileName" character varying(200) NOT NULL,
        "FilePath" character varying(500) NOT NULL,
        "ParsedText" text NOT NULL,
        "WeekStart" date,
        "WeekEnd" date,
        "Remark" character varying(200),
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_WeeklyReportReference" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_WeeklyReportReference_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "WorkLog" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Purpose" character varying(500),
        "Content" text,
        "Tags" character varying(500),
        "Category" character varying(100),
        "LogDate" date NOT NULL,
        "Status" smallint NOT NULL,
        "StatusRemark" character varying(500),
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_WorkLog" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_WorkLog_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "ChatSession" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Title" character varying(200) NOT NULL,
        "ProjectId" integer,
        "IsPinned" boolean NOT NULL,
        "BranchedFromSessionId" integer,
        "BranchedFromMessageId" integer,
        "IsArchived" boolean NOT NULL,
        "SessionType" character varying(20),
        "AttachToType" character varying(20),
        "AttachToObjectId" integer,
        "AiProvider" character varying(50),
        "AiModel" character varying(120),
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_ChatSession" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ChatSession_ChatProject_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "ChatProject" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_ChatSession_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "AgentRun" (
        "Id" uuid NOT NULL,
        "UserId" integer NOT NULL,
        "SessionId" integer NOT NULL,
        "AiProvider" character varying(50),
        "AiModel" character varying(120),
        "Status" character varying(32) NOT NULL,
        "RequestJson" text NOT NULL,
        "CheckpointJson" text,
        "UserMessageId" integer,
        "AssistantMessageId" integer,
        "FailureMessage" text,
        "StartedAt" timestamp with time zone,
        "CompletedAt" timestamp with time zone,
        "LastActivityAt" timestamp with time zone,
        "RecoverableAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_AgentRun" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AgentRun_ChatSession_SessionId" FOREIGN KEY ("SessionId") REFERENCES "ChatSession" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AgentRun_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "ChatMessage" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SessionId" integer NOT NULL,
        "Role" character varying(20) NOT NULL,
        "Content" text NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_ChatMessage" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ChatMessage_ChatSession_SessionId" FOREIGN KEY ("SessionId") REFERENCES "ChatSession" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE TABLE "AgentRunEvent" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RunId" uuid NOT NULL,
        "Sequence" bigint NOT NULL,
        "Type" character varying(50) NOT NULL,
        "DataJson" text NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer NOT NULL,
        CONSTRAINT "PK_AgentRunEvent" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AgentRunEvent_AgentRun_RunId" FOREIGN KEY ("RunId") REFERENCES "AgentRun" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_AgentMemories_UserId" ON "AgentMemories" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_AgentMemories_UserId_Key" ON "AgentMemories" ("UserId", "Key") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_AgentRun_SessionId" ON "AgentRun" ("SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_AgentRun_Status_CreatedAt" ON "AgentRun" ("Status", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_AgentRun_UserId_SessionId_Status" ON "AgentRun" ("UserId", "SessionId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_AgentRunEvent_RunId_Sequence" ON "AgentRunEvent" ("RunId", "Sequence");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_AIActionLogs_TargetType_TargetId" ON "AIActionLogs" ("TargetType", "TargetId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_AIActionLogs_UserId_CreatedAt" ON "AIActionLogs" ("UserId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_ChatMessage_SessionId" ON "ChatMessage" ("SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_ChatMessage_SessionId_CreatedAt" ON "ChatMessage" ("SessionId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_ChatProject_UserId_Name" ON "ChatProject" ("UserId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_ChatSession_ProjectId" ON "ChatSession" ("ProjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_ChatSession_UserId" ON "ChatSession" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_ChatSession_UserId_IsArchived_UpdatedAt" ON "ChatSession" ("UserId", "IsArchived", "UpdatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_ChatSession_UserId_ProjectId_IsPinned_UpdatedAt" ON "ChatSession" ("UserId", "ProjectId", "IsPinned", "UpdatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_ChatSession_UserId_SessionType" ON "ChatSession" ("UserId", "SessionType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_ChatSession_UserId_UpdatedAt" ON "ChatSession" ("UserId", "UpdatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_DailyBriefings_UserId_BriefDate" ON "DailyBriefings" ("UserId", "BriefDate") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_EmailVerifyToken_Token" ON "EmailVerifyToken" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_EmailVerifyToken_UserId" ON "EmailVerifyToken" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_InboxItems_UserId_Status_CreatedAt" ON "InboxItems" ("UserId", "Status", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_LifeLog_UserId_LogDate" ON "LifeLog" ("UserId", "LogDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_Memo_UserId_Section" ON "Memo" ("UserId", "Section");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_RefreshToken_TokenHash" ON "RefreshToken" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_RefreshToken_UserId" ON "RefreshToken" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_ScheduledTask_ExecuteAt" ON "ScheduledTask" ("ExecuteAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_ScheduledTask_UserId_Status" ON "ScheduledTask" ("UserId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_User_Email" ON "User" ("Email") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_User_NormalizedUserName" ON "User" ("NormalizedUserName") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_WeeklyReport_UserId_WeekStart" ON "WeeklyReport" ("UserId", "WeekStart");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_WeeklyReportReference_UserId" ON "WeeklyReportReference" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    CREATE INDEX "IX_WorkLog_UserId_LogDate" ON "WorkLog" ("UserId", "LogDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261007062339_InitialPostgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261007062339_InitialPostgres', '10.0.12');
    END IF;
END $EF$;
COMMIT;

