namespace MiraiNote.Core.Services;

/// <summary>
/// ISO 3166-1 alpha-2。中文和英文是 CLDR 短名，不是和风天气的国家目录。
/// </summary>
internal static class Iso3166Countries
{
    public static readonly RegionCountry[] All =
    [
        new("安道尔", "Andorra", "ad"),
        new("阿拉伯联合酋长国", "United Arab Emirates", "ae"),
        new("阿富汗", "Afghanistan", "af"),
        new("安提瓜和巴布达", "Antigua & Barbuda", "ag"),
        new("安圭拉", "Anguilla", "ai"),
        new("阿尔巴尼亚", "Albania", "al"),
        new("亚美尼亚", "Armenia", "am"),
        new("安哥拉", "Angola", "ao"),
        new("南极洲", "Antarctica", "aq"),
        new("阿根廷", "Argentina", "ar"),
        new("美属萨摩亚", "American Samoa", "as"),
        new("奥地利", "Austria", "at"),
        new("澳大利亚", "Australia", "au"),
        new("阿鲁巴", "Aruba", "aw"),
        new("奥兰群岛", "Åland Islands", "ax"),
        new("阿塞拜疆", "Azerbaijan", "az"),
        new("波斯尼亚和黑塞哥维那", "Bosnia & Herzegovina", "ba"),
        new("巴巴多斯", "Barbados", "bb"),
        new("孟加拉国", "Bangladesh", "bd"),
        new("比利时", "Belgium", "be"),
        new("布基纳法索", "Burkina Faso", "bf"),
        new("保加利亚", "Bulgaria", "bg"),
        new("巴林", "Bahrain", "bh"),
        new("布隆迪", "Burundi", "bi"),
        new("贝宁", "Benin", "bj"),
        new("圣巴泰勒米", "St. Barthélemy", "bl"),
        new("百慕大", "Bermuda", "bm"),
        new("文莱", "Brunei", "bn"),
        new("玻利维亚", "Bolivia", "bo"),
        new("荷属加勒比区", "Caribbean Netherlands", "bq"),
        new("巴西", "Brazil", "br"),
        new("巴哈马", "Bahamas", "bs"),
        new("不丹", "Bhutan", "bt"),
        new("布韦岛", "Bouvet Island", "bv"),
        new("博茨瓦纳", "Botswana", "bw"),
        new("白俄罗斯", "Belarus", "by"),
        new("伯利兹", "Belize", "bz"),
        new("加拿大", "Canada", "ca"),
        new("科科斯（基林）群岛", "Cocos (Keeling) Islands", "cc"),
        new("刚果（金）", "Congo - Kinshasa", "cd"),
        new("中非共和国", "Central African Republic", "cf"),
        new("刚果（布）", "Congo - Brazzaville", "cg"),
        new("瑞士", "Switzerland", "ch"),
        new("科特迪瓦", "Côte d’Ivoire", "ci"),
        new("库克群岛", "Cook Islands", "ck"),
        new("智利", "Chile", "cl"),
        new("喀麦隆", "Cameroon", "cm"),
        new("中国", "China", "cn"),
        new("哥伦比亚", "Colombia", "co"),
        new("哥斯达黎加", "Costa Rica", "cr"),
        new("古巴", "Cuba", "cu"),
        new("佛得角", "Cape Verde", "cv"),
        new("库拉索", "Curaçao", "cw"),
        new("圣诞岛", "Christmas Island", "cx"),
        new("塞浦路斯", "Cyprus", "cy"),
        new("捷克", "Czechia", "cz"),
        new("德国", "Germany", "de"),
        new("吉布提", "Djibouti", "dj"),
        new("丹麦", "Denmark", "dk"),
        new("多米尼克", "Dominica", "dm"),
        new("多米尼加共和国", "Dominican Republic", "do"),
        new("阿尔及利亚", "Algeria", "dz"),
        new("厄瓜多尔", "Ecuador", "ec"),
        new("爱沙尼亚", "Estonia", "ee"),
        new("埃及", "Egypt", "eg"),
        new("西撒哈拉", "Western Sahara", "eh"),
        new("厄立特里亚", "Eritrea", "er"),
        new("西班牙", "Spain", "es"),
        new("埃塞俄比亚", "Ethiopia", "et"),
        new("芬兰", "Finland", "fi"),
        new("斐济", "Fiji", "fj"),
        new("福克兰群岛", "Falkland Islands", "fk"),
        new("密克罗尼西亚", "Micronesia", "fm"),
        new("法罗群岛", "Faroe Islands", "fo"),
        new("法国", "France", "fr"),
        new("加蓬", "Gabon", "ga"),
        new("英国", "United Kingdom", "gb"),
        new("格林纳达", "Grenada", "gd"),
        new("格鲁吉亚", "Georgia", "ge"),
        new("法属圭亚那", "French Guiana", "gf"),
        new("根西岛", "Guernsey", "gg"),
        new("加纳", "Ghana", "gh"),
        new("直布罗陀", "Gibraltar", "gi"),
        new("格陵兰", "Greenland", "gl"),
        new("冈比亚", "Gambia", "gm"),
        new("几内亚", "Guinea", "gn"),
        new("瓜德罗普", "Guadeloupe", "gp"),
        new("赤道几内亚", "Equatorial Guinea", "gq"),
        new("希腊", "Greece", "gr"),
        new("南乔治亚和南桑威奇群岛", "South Georgia & South Sandwich Islands", "gs"),
        new("危地马拉", "Guatemala", "gt"),
        new("关岛", "Guam", "gu"),
        new("几内亚比绍", "Guinea-Bissau", "gw"),
        new("圭亚那", "Guyana", "gy"),
        new("中国香港特别行政区", "Hong Kong SAR China", "hk"),
        new("赫德岛和麦克唐纳群岛", "Heard & McDonald Islands", "hm"),
        new("洪都拉斯", "Honduras", "hn"),
        new("克罗地亚", "Croatia", "hr"),
        new("海地", "Haiti", "ht"),
        new("匈牙利", "Hungary", "hu"),
        new("印度尼西亚", "Indonesia", "id"),
        new("爱尔兰", "Ireland", "ie"),
        new("以色列", "Israel", "il"),
        new("马恩岛", "Isle of Man", "im"),
        new("印度", "India", "in"),
        new("英属印度洋领地", "British Indian Ocean Territory", "io"),
        new("伊拉克", "Iraq", "iq"),
        new("伊朗", "Iran", "ir"),
        new("冰岛", "Iceland", "is"),
        new("意大利", "Italy", "it"),
        new("泽西岛", "Jersey", "je"),
        new("牙买加", "Jamaica", "jm"),
        new("约旦", "Jordan", "jo"),
        new("日本", "Japan", "jp"),
        new("肯尼亚", "Kenya", "ke"),
        new("吉尔吉斯斯坦", "Kyrgyzstan", "kg"),
        new("柬埔寨", "Cambodia", "kh"),
        new("基里巴斯", "Kiribati", "ki"),
        new("科摩罗", "Comoros", "km"),
        new("圣基茨和尼维斯", "St. Kitts & Nevis", "kn"),
        new("朝鲜", "North Korea", "kp"),
        new("韩国", "South Korea", "kr"),
        new("科威特", "Kuwait", "kw"),
        new("开曼群岛", "Cayman Islands", "ky"),
        new("哈萨克斯坦", "Kazakhstan", "kz"),
        new("老挝", "Laos", "la"),
        new("黎巴嫩", "Lebanon", "lb"),
        new("圣卢西亚", "St. Lucia", "lc"),
        new("列支敦士登", "Liechtenstein", "li"),
        new("斯里兰卡", "Sri Lanka", "lk"),
        new("利比里亚", "Liberia", "lr"),
        new("莱索托", "Lesotho", "ls"),
        new("立陶宛", "Lithuania", "lt"),
        new("卢森堡", "Luxembourg", "lu"),
        new("拉脱维亚", "Latvia", "lv"),
        new("利比亚", "Libya", "ly"),
        new("摩洛哥", "Morocco", "ma"),
        new("摩纳哥", "Monaco", "mc"),
        new("摩尔多瓦", "Moldova", "md"),
        new("黑山", "Montenegro", "me"),
        new("法属圣马丁", "St. Martin", "mf"),
        new("马达加斯加", "Madagascar", "mg"),
        new("马绍尔群岛", "Marshall Islands", "mh"),
        new("北马其顿", "North Macedonia", "mk"),
        new("马里", "Mali", "ml"),
        new("缅甸", "Myanmar (Burma)", "mm"),
        new("蒙古", "Mongolia", "mn"),
        new("中国澳门特别行政区", "Macao SAR China", "mo"),
        new("北马里亚纳群岛", "Northern Mariana Islands", "mp"),
        new("马提尼克", "Martinique", "mq"),
        new("毛里塔尼亚", "Mauritania", "mr"),
        new("蒙特塞拉特", "Montserrat", "ms"),
        new("马耳他", "Malta", "mt"),
        new("毛里求斯", "Mauritius", "mu"),
        new("马尔代夫", "Maldives", "mv"),
        new("马拉维", "Malawi", "mw"),
        new("墨西哥", "Mexico", "mx"),
        new("马来西亚", "Malaysia", "my"),
        new("莫桑比克", "Mozambique", "mz"),
        new("纳米比亚", "Namibia", "na"),
        new("新喀里多尼亚", "New Caledonia", "nc"),
        new("尼日尔", "Niger", "ne"),
        new("诺福克岛", "Norfolk Island", "nf"),
        new("尼日利亚", "Nigeria", "ng"),
        new("尼加拉瓜", "Nicaragua", "ni"),
        new("荷兰", "Netherlands", "nl"),
        new("挪威", "Norway", "no"),
        new("尼泊尔", "Nepal", "np"),
        new("瑙鲁", "Nauru", "nr"),
        new("纽埃", "Niue", "nu"),
        new("新西兰", "New Zealand", "nz"),
        new("阿曼", "Oman", "om"),
        new("巴拿马", "Panama", "pa"),
        new("秘鲁", "Peru", "pe"),
        new("法属波利尼西亚", "French Polynesia", "pf"),
        new("巴布亚新几内亚", "Papua New Guinea", "pg"),
        new("菲律宾", "Philippines", "ph"),
        new("巴基斯坦", "Pakistan", "pk"),
        new("波兰", "Poland", "pl"),
        new("圣皮埃尔和密克隆群岛", "St. Pierre & Miquelon", "pm"),
        new("皮特凯恩群岛", "Pitcairn Islands", "pn"),
        new("波多黎各", "Puerto Rico", "pr"),
        new("巴勒斯坦领土", "Palestinian Territories", "ps"),
        new("葡萄牙", "Portugal", "pt"),
        new("帕劳", "Palau", "pw"),
        new("巴拉圭", "Paraguay", "py"),
        new("卡塔尔", "Qatar", "qa"),
        new("留尼汪", "Réunion", "re"),
        new("罗马尼亚", "Romania", "ro"),
        new("塞尔维亚", "Serbia", "rs"),
        new("俄罗斯", "Russia", "ru"),
        new("卢旺达", "Rwanda", "rw"),
        new("沙特阿拉伯", "Saudi Arabia", "sa"),
        new("所罗门群岛", "Solomon Islands", "sb"),
        new("塞舌尔", "Seychelles", "sc"),
        new("苏丹", "Sudan", "sd"),
        new("瑞典", "Sweden", "se"),
        new("新加坡", "Singapore", "sg"),
        new("圣赫勒拿", "St. Helena", "sh"),
        new("斯洛文尼亚", "Slovenia", "si"),
        new("斯瓦尔巴和扬马延", "Svalbard & Jan Mayen", "sj"),
        new("斯洛伐克", "Slovakia", "sk"),
        new("塞拉利昂", "Sierra Leone", "sl"),
        new("圣马力诺", "San Marino", "sm"),
        new("塞内加尔", "Senegal", "sn"),
        new("索马里", "Somalia", "so"),
        new("苏里南", "Suriname", "sr"),
        new("南苏丹", "South Sudan", "ss"),
        new("圣多美和普林西比", "São Tomé & Príncipe", "st"),
        new("萨尔瓦多", "El Salvador", "sv"),
        new("荷属圣马丁", "Sint Maarten", "sx"),
        new("叙利亚", "Syria", "sy"),
        new("斯威士兰", "Eswatini", "sz"),
        new("特克斯和凯科斯群岛", "Turks & Caicos Islands", "tc"),
        new("乍得", "Chad", "td"),
        new("法属南部领地", "French Southern Territories", "tf"),
        new("多哥", "Togo", "tg"),
        new("泰国", "Thailand", "th"),
        new("塔吉克斯坦", "Tajikistan", "tj"),
        new("托克劳", "Tokelau", "tk"),
        new("东帝汶", "Timor-Leste", "tl"),
        new("土库曼斯坦", "Turkmenistan", "tm"),
        new("突尼斯", "Tunisia", "tn"),
        new("汤加", "Tonga", "to"),
        new("土耳其", "Turkey", "tr"),
        new("特立尼达和多巴哥", "Trinidad & Tobago", "tt"),
        new("图瓦卢", "Tuvalu", "tv"),
        new("台湾", "Taiwan", "tw"),
        new("坦桑尼亚", "Tanzania", "tz"),
        new("乌克兰", "Ukraine", "ua"),
        new("乌干达", "Uganda", "ug"),
        new("美国本土外小岛屿", "U.S. Outlying Islands", "um"),
        new("美国", "United States", "us"),
        new("乌拉圭", "Uruguay", "uy"),
        new("乌兹别克斯坦", "Uzbekistan", "uz"),
        new("梵蒂冈", "Vatican City", "va"),
        new("圣文森特和格林纳丁斯", "St. Vincent & Grenadines", "vc"),
        new("委内瑞拉", "Venezuela", "ve"),
        new("英属维尔京群岛", "British Virgin Islands", "vg"),
        new("美属维尔京群岛", "U.S. Virgin Islands", "vi"),
        new("越南", "Vietnam", "vn"),
        new("瓦努阿图", "Vanuatu", "vu"),
        new("瓦利斯和富图纳", "Wallis & Futuna", "wf"),
        new("萨摩亚", "Samoa", "ws"),
        new("也门", "Yemen", "ye"),
        new("马约特", "Mayotte", "yt"),
        new("南非", "South Africa", "za"),
        new("赞比亚", "Zambia", "zm"),
        new("津巴布韦", "Zimbabwe", "zw"),
    ];
}
